name: Continuous Integration

on: 
  push:
    paths-ignore:
      - "README.md"
  pull_request:
    paths-ignore:
      - "README.md"


jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: docker build --tag todo-app:test --target test .
    - run: docker run todo-app:test

  deploy:
    name: push to Docker hub and trigger App Service Deploy
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/Exercise9' }}
    steps:
      - uses: actions/checkout@v4

      - run: echo hello deploy

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - run: docker build --tag vtambe/todo-app:prod --target production .

      - run: docker push vtambe/todo-app:prod

      - name: Call Azure App Service webhook
        env:
          AZURE_WEBHOOK: ${{ secrets.AZURE_WEBHOOK }}
        run: curl -v -X POST "$AZURE_WEBHOOK"